/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package handson;

import java.util.Arrays;
import java.util.HashMap;
import java.util.TreeMap;
import java.util.stream.IntStream;

import javax.swing.RowFilter.Entry;

import org.w3c.dom.Node;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        
        System.out.println(new App().getGreeting());
        TreeMap<Integer,Integer> map = new TreeMap<>();

IntStream.range(1, 200).parallel().forEach(e -> map.put(e, e));

        map.entrySet().forEach(e -> System.out.println(e.getKey()+","+e.getValue()));

        
        //  if(map instanceof HashMap){
        // HashMap<Integer,String> clonedMap = (HashMap<Integer, String>) map.clone();
        // clonedMap.put(1,"2");
        // System.out.println(map);
        // System.out.println(clonedMap);
        //  }




    }
}
